[build]
  publish = "dist/public/"
  command = "npm run build"
  functions = "dist/functions/"

[[redirects]]
  from = "/libraries/*"
  to = "/.netlify/functions/submit"
  status = 200

[[redirects]]
  from = "/github-auth/client-id"
  to = "/.netlify/functions/auth-client-id"
  status = 200

[[redirects]]
  from = "/github-auth/auth"
  to = "/.netlify/functions/auth"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
