[build]
  publish = "dist/public/"
  command = "npm run build"
  functions = "dist/functions/"

[[redirects]]
  from = "/data/libraries/*"
  to = "/.netlify/functions/submit"
  status = 200

[[redirects]]
  from = "/preload/*"
  to = "http://slate-hlm.netlify.app/preload/:splat"
  status = 200

[[redirects]]
  from = "/github-auth/info"
  to = "/.netlify/functions/auth-info"
  status = 200

[[redirects]]
  from = "/github-auth/auth"
  to = "/.netlify/functions/auth"
  status = 200

[[redirects]]
  from = "/libraries/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/docs/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200
