[build]
  publish = "dist/public/"
  command = "npm run build"
  functions = "dist/functions/"

[[redirects]]
  from = "/*.*"
  to = "/:splat"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/github-auth/*"
  to = "/.netlify/functions/github-auth/:splat"
  status = 200

[[redirects]]
  from = "/libraries/*"
  to = "/.netlify/functions/submit"
  status = 200
