import * as express from 'express';
import * as path from 'path';

export function appRouter(rootPath: string): express.Router {
  const router = express.Router();

  const publicPath = path.join(rootPath, 'dist', 'public');

  // All the assets are in "public" folder (Done by build.js)
  router.use(express.static(publicPath));

  // Any route without a dot should render the web app html (Generated by build.js)
  router.get('**', (req, res) => res.sendFile(path.join(publicPath, 'index.html')));

  return router;
}
