import * as express from 'express';
import * as path from 'path';
import { handleSubmit } from 'slate-server-generic/handlers/submitHandler';

export function prodRouter(rootPath: string): express.Router {
  const router = express.Router();

  const publicPath = path.join(rootPath, 'dist', 'public');

  router.put('/data/libraries/*', handleSubmit);

  // All the assets are in "public" folder (Done by Webpack)
  router.use(express.static(publicPath));

  // Any route without a dot should render the web app html (Generated by Webpack)
  router.get('**', (req, res) => res.sendFile(path.join(publicPath, 'index.html')));

  return router;
}
