import * as express from 'express';
import * as path from 'path';
import * as nodemailer from 'nodemailer';
import * as config from '../config';

function submitByMail(request: express.Request, response: express.Response, mailTransporter: nodemailer.Transporter | undefined): void {
  if (mailTransporter && config.MAIL_FROM && config.MAIL_TO) {
    let requestPath = decodeURI(request.url);
    let mail: any = {
      from: config.MAIL_FROM,
      to: config.MAIL_TO,
      subject: 'Slate submission: ' + requestPath,
      text: requestPath,
      attachments: [{
        filename: path.basename(requestPath),
        contentType: 'text/plain',
        contentTransferEncoding: 'quoted-printable',
        content: request
      }]
    };
    mailTransporter.sendMail(mail, (error) => {
      if (error) {
        console.error(error);
        response.sendStatus(503);
      } else {
        response.sendStatus(202);
      }
    });
  } else {
    response.sendStatus(501);
  }
}

export function prodRouter(rootPath: string): express.Router {
  let router = express.Router();

  let publicPath = path.join(rootPath, 'dist', 'public');

  let mailTransporter = config.MAIL_TRANSPORT_CONFIG ? nodemailer.createTransport(config.MAIL_TRANSPORT_CONFIG) : undefined;

  router.put('/libraries/*', (request, response) => {
    console.log(`Received PUT request for: ${request.url}`);
    submitByMail(request, response, mailTransporter);
  });

  // All the assets are in "public" folder (Done by Webpack)
  router.use(express.static(publicPath));

  // Any route without a dot should render the web app html (Generated by Webpack)
  router.get('**', (req, res) => res.sendFile(path.join(publicPath, 'index.html')));

  return router;
}
