name: Run tests
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Cache NPM dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('package-lock.json') }}
      - name: Install NPM dependencies
        run: npm install
      - name: Check dependencies
        run: npm run depcruise
        timeout-minutes: 2
      - name: Run tests
        run: npm run test
        timeout-minutes: 10
